### ISSUE TITLE
when show = False , the figure is not saved.

### ISSUE THREAD

**Issue by KerenHagitStern** [endangeredoxen/fivecentplots#46]
when show = False
the figure is not saved.
the solution I found is to delete row 1614 under the plotter function:
"if kwargs.get('save', False) or kwargs.get('show', False):"

Great package!
thanks

**Comment by endangeredoxen** [comment]
Thanks for the kind feedback.  This is expected behavior in v0.5.0.  If you look [at the docs here](https://endangeredoxen.github.io/fivecentplots/0.5.0/api/options.html#options) you see the default for keyword `save` is `False`.  So if you want to save and not show, add `save=True` and `show=False` in your kwargs.  

If you want to make and save plots in the background without showing them in a pop-up window or in a notebook output cell, you can also add `inline=False` and the plot will be saved in the background without displaying.  Let me know if you have any questions about this
