### ISSUE TITLE
AttributeError: 'Line2D' object has no attribute '_legmarker'

### ISSUE THREAD

**Issue by frecloud** [endangeredoxen/fivecentplots#48]
When I am passing legend parameter I am getting this error.
![Screenshot 2022-09-13 232651](https://user-images.githubusercontent.com/104160748/189978670-ab189a36-d1dc-4d46-bcc8-94f7555d79a3.jpg)
If I don't pass legend, It works fine

**Comment by endangeredoxen** [comment]
What versions of fcp and matplotlib are you using?

**Comment by endangeredoxen** [comment]
Ok I suspected this.  It is a known bug but I haven't had time to patch it because I'm focused on releasing v0.5.0.  fcp 0.4.3 doesn't support matplotlib 3.5.3.

You can either downgrade your matplotlib (don't recall exactly which version works but around 3.1 I think) or upgrade to the beta version of fcp v0.5.0 (`pip install fivecentplots==0.5.0b2`)

Sorry for the inconvenience!

**Comment by endangeredoxen** [comment]
OK I decided to patch this after all since the newer version is still beta so now you can use v0.4.4 to avoid the legmarker issue with mpl 3.5.3.  `pip install fivecentplots --force-reinstall` should take care of the upgrade for you.  

But I strongly encourage migration to v0.5.0 when released as it improves on a lot of issues with v0.4.4.  Cheers!

**Comment by endangeredoxen** [comment]
Ok I suspected this.  It is a known bug but I haven't had time to patch it
because I'm focused on releasing v0.5.0.  fcp 0.4.3 doesn't support
matplotlib 3.5.3.

You can either downgrade your matplotlib (don't recall exactly which
version works but around 3.1 I think) or upgrade to the beta version of fcp
v0.5.0 (pip install fivecentplots==0.5.0b2)

Sorry for the inconvenience!
